### ISSUE TITLE
Awesome website!

### ISSUE THREAD

**Issue by wrbird** [bfkeinberg/route-forecast#26]
You created an awesome website.  Have you considered developing an android app?  I can see the essential data on my phone using Chrome, but I can't see the map or control points table.  This is definitely better than nothing when I don't have PC access, but it would be totally awesome to have all the features available on the phone.

**Comment by bfkeinberg** [comment]
I actually turned off those features deliberately on small screens. I'm
considering turning that back on, even though I'm not sure how usable it
would be.

Longer term, since this is a React application, I'm thinking of building
one with React Native, which would (theoretically) let me deploy it as a
iOS or Android application. It would be a fun exercise, so I am tempted.
