### ISSUE TITLE
Route colors - what do they mean?

### ISSUE THREAD

**Issue by palincss** [bfkeinberg/route-forecast#34]
Portions of the route (sometimes) turn green as I mouse down the table to the left of the route.  I say sometimes because it's inconsistent and doesn't happen always.  Does this mean this is the section of the route for this chunk of time?  If not that, what does the color mean?  It would be nice if there was some documentation explaining what's going on, but if it exists I've missed it.

**Comment by wrbird** [comment]
I'm not the developer, but what I've seen so far is that the color change to green is the section of time that is highlighted on the left side, just as you stated.  It has always worked for me, with no inconsistencies.  However, maybe what you're seeing (or really not seeing) when a section isn't highlighting is because it's such a short segment of time.  For example, depending on when my ride ends it might be such a small change in time from that last forecast that when I do mouse over it, it doesn't show as green.  I hope this helps.  

I don't want to speak on behalf on the developer, but my guess why there's no documentation is because of limited resources.  It's not like this website is developed by some large company.  But what he has done has been excellent.

**Comment by bfkeinberg** [comment]
Sorry if it's confusing. Yes, the highlighting is the section of route for
that chunk of time.
