### ISSUE TITLE
when clicking on ride segments the map zooms far out, sometimes the ocean

### ISSUE THREAD

**Issue by sanmi** [bfkeinberg/route-forecast#48]
Steps to reproduce:
* enter route 31831394, 14mph, 1 hour segments
* click on the segment "mile 0", map zooms to all blue in the pacific ocean (probably lat/lon (0,0)
* click on the second segment "mile 14", map zooms far out
* other zooms don't highlight the segments

![image](https://user-images.githubusercontent.com/541993/73274455-701ded80-419a-11ea-90ec-3dbb90715ee3.png)

**Comment by sanmi** [comment]
Sorry to say that I have since modified the route and now I can't reproduce the behavior!

**Comment by bfkeinberg** [comment]
That's curious. I just tried to repro to no avail.

**Comment by bfkeinberg** [comment]
Tried again, still won't do it for me. On latest Chrome?

**Comment by bfkeinberg** [comment]
Wow, finally figured this out. But I don't have an idea on how to fix it. The problem is that the feature uses the route data provided by ridewithgps to get the distance at each point in the route, and compares with the start and end distance in a segment. Sometimes ridewithgps doesn't include the distance in the route points. It probably makes the most sense to just disable this feature when there's no distance in the route points.
